name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (with legacy peer deps)
        run: npm install --legacy-peer-deps

      - name: Generate build version and inject to version.ts
        run: |
          VERSION_DATE=$(date +'%Y-%m-%d')
          VERSION_HASH=$(git rev-parse --short HEAD)
          VERSION="v${VERSION_DATE}-${VERSION_HASH}"
          echo "Generated version: $VERSION"
          sed -i "s/__VERSION_PLACEHOLDER__/$VERSION/" src/version.ts

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
